import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <head>
        <meta charSet="utf-8" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta content="width=device-width, initial-scale=1" name="viewport" />

        {/* <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href={inter.href} /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
